[buildpack]
name = "Gradle"

[publish.Ignore]
files = [
  ".github/",
  "etc/",
  "test/",
  ".gitignore",
  ".rubocop.yml",
  "Gemfile",
  "Gemfile.lock",
  "hatchet.json",
  "hatchet.lock",
  "Makefile",
]
